# PROVIDED VARS BY RUN SCRIPT:
#  * TIMESTAMP
#  * BUCKET_NAME
#  * INSTANCE_NUMBER
#  * SCALE
cd ~

export TARRED_CODE="parallel.tar.gz"
export SOURCE_CODE_PATH="gs://$BUCKET_NAME/$TARRED_CODE"

gsutil cp $SOURCE_CODE_PATH $TARRED_CODE

tar -xzf $TARRED_CODE

./sequential/controller.sh $TIMESTAMP $BUCKET_NAME $INSTANCE_NUMBER $SCALE

